'use strict';

const express = require('express');
const path = require('path');

const app = express();
var port = process.env.PORT || 3000;

/* Serve the static files generated by the CLI (index.html, CSS? JS, assets...) */
app.use(express.static(path.join(__dirname, 'dist/' + process.env.APP)));

/* Direct all routes to index.html, where Angular will take care of routing */
app.get('*', function(req, res) {
    res.sendFile(path.join(__dirname, 'dist/' + process.env.APP + '/index.html'));
});

app.listen(port, function() {
    console.log('Expresslistening on port ' + port + '!');
});